site_name: Eric025's Blog
site_author: Eric025

nav:
  - 主页:
    - index.md
  - Web相关:
    - 如何搭建个人博客 : Web/mkdocs.md

theme:
  name: material
  features:
    - navigation.tabs
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
