site_name: Eric025's Blog
site_author: Eric025

nav:
  - index.md
  - Web相关:
    - 如何搭建个人博客 : Web/mkdocs.md

repo_url: https://github.com/erix025/erix025.github.io
repo_name: erix025.github.io

theme:
  font:
    text: Noto Sans Simplified Chinese
    code: JetBrains Mono
  name: material
  features:
    - navigation.tabs
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
