site_name: Eric025's Blog
site_author: Eric025

nav:
  - index.md
  - Efficient AI:
      - MIT 6.5940: 
          - 课程介绍: EfficientAI/MIT6.5940/Introduction.md
          - Pruning: EfficientAI/MIT6.5940/Pruning.md
  - Web相关:
      - 如何搭建个人博客: Web/mkdocs.md
  - 其他:
      - 微信聊天记录分析: Others/WeChatAnalysis.md
      - Python库打包上传: Others/PythonPackup.md

repo_url: https://github.com/erix025/erix025.github.io
repo_name: erix025.github.io

theme:
  font:
    text: Noto Sans Simplified Chinese
    code: JetBrains Mono
  name: material
  color: pink
  features:
    - navigation.tabs
    - content.code.copy
  palette:
    - primary: blue grey
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
